# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/vlsilab/Desktop/combination/combination.cache/wt [current_project]
set_property parent.project_path C:/Users/vlsilab/Desktop/combination/combination.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet c:/Users/vlsilab/Desktop/combination/combination.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files c:/Users/vlsilab/Desktop/combination/combination.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/vlsilab/Desktop/obstacle_2/obstacle_2.srcs/sources_1/new/vga_controller.v
  C:/Users/vlsilab/Desktop/combination/combination.srcs/sources_1/new/combination.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/vlsilab/Desktop/combination/combination.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files C:/Users/vlsilab/Desktop/combination/combination.srcs/constrs_1/new/constraint.xdc]


synth_design -top combination -part xc7a100tcsg324-1


write_checkpoint -force -noxdef combination.dcp

catch { report_utilization -file combination_utilization_synth.rpt -pb combination_utilization_synth.pb }
